### ISSUE TITLE
Network Connectivity Issue

### ISSUE THREAD

**Issue by skrenek** [aerisweather/AerisAndroidSDK#11]
I have an Android device that is ethernet only.  No mobile or wifi connection available on it.  Even though I'm wired in, Observation callbacks report NO NETWORK; No Mobile of wifi connection is available.

**Comment by sshie** [comment]
Hi Steve,

We did a little digging and the library isn't specifying a certain type of network connection, and we have not seen that error while testing with wifi disabled. Of course, that's not exactly the same as your situation, since our test hardware isn't physically limited to ethernet only. 

The message you're seeing is returned from the isOnline() function, and indicates that either the application context is null, or the network service hasn't been able to establish a connection. Here's the code for that function:

```
public static boolean isOnline(Context context)
{
    boolean ret = false;

	if (context == null)
        {
		ret = false;
	}
        ConnectivityManager connManager = (ConnectivityManager) context.getSystemService(Service.CONNECTIVITY_SERVICE);
        NetworkInfo network = connManager.getActiveNetworkInfo();

	if (network != null)
		ret = network.isConnected();

	return ret;
}
```

I hope that helps point you in the right direction, and please feel free to post your solution when you get it working!

Thanks!

**Comment by skrenek** [comment]
Thanks for the window into the source.  I'll take a deeper look by replicating that function in my own code (so I can debug it) and let you know what I find.

**Comment by skrenek** [comment]
I figured it out.  Due to an outdated readme.md, I was using version 1.2 of the SDK from the com.hamweather package. That package has the following isOnline function.  I submitted a PR to update the README.

```
public static boolean isOnline(Context context) {
        boolean retval = false;
        if(context == null) {
            return false;
        } else {
            ConnectivityManager connManager = (ConnectivityManager)context.getSystemService("connectivity");
            NetworkInfo mWifi = connManager.getNetworkInfo(1);
            NetworkInfo network = connManager.getNetworkInfo(0);
            Boolean wifiConnected = Boolean.valueOf(mWifi != null && mWifi.isConnected());
            Boolean networkConnected = Boolean.valueOf(network != null && network.isConnected());
            if(AerisEngine.getInstance().isDebugLogcatEnabled()) {
                Logger.v(TAG, "Wifi connection is: " + String.valueOf(wifiConnected));
                Logger.v(TAG, "Network connection is: " + String.valueOf(networkConnected));
            }

            retval = wifiConnected.booleanValue() || networkConnected.booleanValue();
            return retval;
        }
    }
```

**Comment by sshie** [comment]
Thanks for the update and the pull request! We've updated the readme in the dev branch and will make sure it gets included in the master during the release process for 2.4.0.
